# DocGen default Pandoc metadata file
#pandoc default metadata file

# toc
toc: true
toc-depth: 2
numbersections: true

# geometry
papersize: A4
documentclass: report
# geometry: margin=top=1in, bottom=1in, left=1in, right=1in


colorlinks: true
linkcolor: magenta
urlcolor: blue
citecolor: blue

# Header / Footer
# header-includes: |
#   \usepackage{fancyhdr}
#   \pagestyle{fancy}
#   \fancyhf{}
#   \fancyhead[L]{\leftmark}
#   \fancyhead[R]{\thepage}
#   \fancyfoot[C]{\thepage}
#   \renewcommand{\headrulewidth}{0.4pt}
#   \renewcommand{\footrulewidth}{0.4pt}

