# DocGen default Pandoc metadata file
#pandoc default metadata file

# Default PDF configuration
pdf-engine: xelatex
standalone: true

# toc
toc: true
toc-depth: 2
numbersections: true

# geometry
papersize: A4
documentclass: report
geometry:
  - top=0.8in
  - bottom=0.8in
  - left=0.8in
  - right=0.8in


colorlinks: true
linkcolor: magenta
urlcolor: blue
citecolor: blue

# Header / Footer
# header-includes: |
#   \usepackage{fancyhdr}
#   \pagestyle{fancy}
#   \fancyhf{}
#   \fancyhead[L]{\leftmark}
#   \fancyhead[R]{\thepage}
#   \fancyfoot[C]{\thepage}
#   \renewcommand{\headrulewidth}{0.4pt}
#   \renewcommand{\footrulewidth}{0.4pt}

